In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("financial_transactions.csv")

In [4]:
df

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [5]:
df.shape

(500, 10)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  500 non-null    int64
 1   Date            500 non-null    object
 2   Customer        500 non-null    object
 3   Category        500 non-null    object
 4   Product         500 non-null    object
 5   Quantity        500 non-null    int64
 6   Sales           500 non-null    int64
 7   Profit          500 non-null    int64
 8   Payment_Method  500 non-null    object
 9   Region          500 non-null    object
dtypes: int64(4), object(6)
memory usage: 39.2+ KB

In [7]:
df["Date"]=pd.to_datetime(df["Date"])
df.dtypes

Transaction_ID             int64
Date              datetime64[ns]
Customer                  object
Category                  object
Product                   object
Quantity                   int64
Sales                      int64
Profit                     int64
Payment_Method            object
Region                    object
dtype: object

In [8]:
df.tail()

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [9]:
df.head()

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North

In [10]:
df.describe()

,Transaction_ID,Date,Quantity,Sales,Profit
count,500.000000,500,500.000000,500.000000,500.00000
mean,250.500000,2026-04-28 06:08:38.400000,5.588000,77935.808000,14718.44400
min,1.000000,2026-01-01 00:00:00,1.000000,111.000000,11.00000
25%,125.750000,2026-03-01 00:00:00,3.000000,6823.250000,1203.75000
50%,250.500000,2026-04-24 12:00:00,6.000000,20646.000000,3654.00000
75%,375.250000,2026-06-26 00:00:00,8.000000,94242.000000,16099.50000
max,500.000000,2026-08-30 00:00:00,10.000000,747490.000000,156830.00000
std,144.481833,NaN,2.884944,122810.672351,25053.37623

In [11]:
high_sales=df[df['Sales']>60000]
high_sales

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South
14,15,2026-04-22,Priya,Electronics,Keyboard,5,230435,24090,UPI,North
15,16,2026-08-11,Divya,Furniture,Desk,3,105813,29709,Net Banking,South
...,...,...,...,...,...,...,...,...,...,...
485,486,2026-04-09,Pooja,Electronics,Monitor,10,436840,83394,Net Banking,South
486,487,2026-02-04,Vijay,Furniture,Bookshelf,6,127668,22932,UPI,East
492,493,2026-07-10,Swathi,Furniture,Bookshelf,2,77646,20985,UPI,South
494,495,2026-08-22,Neha,Electronics,Headphones,4,238292,62574,Net Banking,South
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North

In [12]:
high_profit=df[df['Profit']>60000]
high_profit

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
40,41,2026-05-24,Arun,Furniture,Table,8,305232,71804,Cash,North
63,64,2026-04-17,Meena,Electronics,Monitor,7,314083,62620,Credit Card,West
109,110,2026-05-10,Akhil,Electronics,Headphones,7,322336,92038,Cash,East
110,111,2026-04-25,Swathi,Furniture,Desk,10,340890,92162,UPI,East
115,116,2026-08-07,Ravi,Furniture,Sofa,10,280490,62539,Net Banking,West
128,129,2026-07-25,Swathi,Electronics,Smartphone,4,214356,62763,Debit Card,North
142,143,2026-01-28,Lakshmi,Electronics,Laptop,8,433120,75267,UPI,North
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West
166,167,2026-07-14,Aditya,Electronics,Smartphone,8,498488,122617,UPI,East
169,170,2026-05-29,Swathi,Electronics,Laptop,10,679620,111856,Cash,West
183,184,2026-02-07,Pooja,Electronics,Smartphone,5,301965,84298,Cash,South
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West
210,211,2026-05-22,Vijay,Electronics,Headphones,9,448677,82031,Net Banking,North
211,212,2026-07-16,Pooja,Electronics,Headphones,7,449673,87979,Net Banking,North
265,266,2026-07-06,Sneha,Electronics,Smartphone,9,477162,93688,Cash,North
277,278,2026-02-23,Ravi,Electronics,Smartphone,10,747490,95487,Debit Card,North
282,283,2026-03-17,Vijay,Furniture,Desk,10,399540,95251,Credit Card,East
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West
288,289,2026-03-15,Arun,Electronics,Laptop,9,337590,66796,Net Banking,West
298,299,2026-03-25,Arun,Electronics,Headphones,10,534960,156830,Debit Card,West
304,305,2026-07-05,Swathi,Electronics,Headphones,7,366303,92094,Credit Card,South
343,344,2026-07-31,Kiran,Electronics,Keyboard,7,210357,61632,UPI,East
379,380,2026-01-31,Swathi,Electronics,Smartphone,8,500688,74646,Debit Card,South
397,398,2026-03-29,Priya,Electronics,Headphones,10,279060,71835,Debit Card,North
405,406,2026-02-12,Pooja,Electronics,Laptop,7,412566,99497,UPI,West
471,472,2026-02-27,Ravi,Furniture,Chair,9,358119,85672,Net Banking,North
473,474,2026-08-11,Priya,Electronics,Smartphone,9,567090,151646,Cash,West
477,478,2026-05-24,Kiran,Electronics,Keyboard,10,414240,114257,UPI,East
485,486,2026-04-09,Pooja,Electronics,Monitor,10,436840,83394,Net Banking,South
494,495,2026-08-22,Neha,Electronics,Headphones,4,238292,62574,Net Banking,South

In [13]:
categort_avg=df[df["Category"] == "Furniture"]
categort_avg

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South
15,16,2026-08-11,Divya,Furniture,Desk,3,105813,29709,Net Banking,South
23,24,2026-08-28,Aditya,Furniture,Bookshelf,4,149356,16296,Net Banking,West
26,27,2026-04-25,Vijay,Furniture,Chair,4,58224,7094,UPI,South
27,28,2026-08-09,Swathi,Furniture,Bookshelf,4,27760,4927,Cash,North
...,...,...,...,...,...,...,...,...,...,...
478,479,2026-07-16,Anjali,Furniture,Chair,4,127132,19455,Net Banking,West
479,480,2026-02-26,Arun,Furniture,Bookshelf,2,16770,4143,Debit Card,East
480,481,2026-01-12,Priya,Furniture,Desk,9,238527,55925,UPI,South
486,487,2026-02-04,Vijay,Furniture,Bookshelf,6,127668,22932,UPI,East
492,493,2026-07-10,Swathi,Furniture,Bookshelf,2,77646,20985,UPI,South

In [14]:
df[(df["Sales"] > 40000) & (df["Product"] == "Bookshelf")]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South
23,24,2026-08-28,Aditya,Furniture,Bookshelf,4,149356,16296,Net Banking,West
30,31,2026-03-17,Kiran,Furniture,Bookshelf,9,305046,34792,Cash,North
50,51,2026-06-19,Anu,Furniture,Bookshelf,2,47278,10263,Debit Card,East
126,127,2026-05-19,Neha,Furniture,Bookshelf,3,45477,4960,Net Banking,East
222,223,2026-03-16,Manoj,Furniture,Bookshelf,4,44928,4551,Net Banking,West
236,237,2026-04-16,Nikhil,Furniture,Bookshelf,3,87189,20220,Net Banking,West
253,254,2026-03-26,Divya,Furniture,Bookshelf,4,125108,30754,Net Banking,North
266,267,2026-07-30,Sneha,Furniture,Bookshelf,9,268155,52833,Credit Card,West
320,321,2026-04-26,Ravi,Furniture,Bookshelf,2,61430,14671,Cash,East
342,343,2026-08-11,Rahul,Furniture,Bookshelf,8,187592,39024,UPI,East
354,355,2026-06-15,Rahul,Furniture,Bookshelf,6,66978,9009,Credit Card,East
365,366,2026-07-02,Aditya,Furniture,Bookshelf,5,181655,17084,Cash,West
399,400,2026-03-24,Vijay,Furniture,Bookshelf,10,86210,13280,Credit Card,West
427,428,2026-06-04,Rahul,Furniture,Bookshelf,6,117936,28344,Credit Card,West
432,433,2026-08-11,Lakshmi,Furniture,Bookshelf,10,312350,37191,Net Banking,East
461,462,2026-05-08,Kiran,Furniture,Bookshelf,5,62550,5546,UPI,East
486,487,2026-02-04,Vijay,Furniture,Bookshelf,6,127668,22932,UPI,East
492,493,2026-07-10,Swathi,Furniture,Bookshelf,2,77646,20985,UPI,South

In [15]:
df[(df["Sales"]>50000) | (df["Profit"]>80000)]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South
10,11,2026-04-28,Vijay,Clothing,Dress,7,54229,15249,Debit Card,South
14,15,2026-04-22,Priya,Electronics,Keyboard,5,230435,24090,UPI,North
...,...,...,...,...,...,...,...,...,...,...
485,486,2026-04-09,Pooja,Electronics,Monitor,10,436840,83394,Net Banking,South
486,487,2026-02-04,Vijay,Furniture,Bookshelf,6,127668,22932,UPI,East
492,493,2026-07-10,Swathi,Furniture,Bookshelf,2,77646,20985,UPI,South
494,495,2026-08-22,Neha,Electronics,Headphones,4,238292,62574,Net Banking,South
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North

In [16]:
df.sort_values('Profit')

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West
...,...,...,...,...,...,...,...,...,...,...
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West
473,474,2026-08-11,Priya,Electronics,Smartphone,9,567090,151646,Cash,West
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West
298,299,2026-03-25,Arun,Electronics,Headphones,10,534960,156830,Debit Card,West

In [17]:
df.sort_values('Sales')

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North
...,...,...,...,...,...,...,...,...,...,...
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West
169,170,2026-05-29,Swathi,Electronics,Laptop,10,679620,111856,Cash,West
277,278,2026-02-23,Ravi,Electronics,Smartphone,10,747490,95487,Debit Card,North

In [18]:
Category_sales=df.groupby("Category")["Sales"].sum()
Category_sales

Category
Clothing        2248310
Electronics    22256321
Furniture      13063762
Grocery          797596
Stationery       601915
Name: Sales, dtype: int64

In [19]:
Category=df.groupby("Category")[["Sales","Profit"]].sum()
Category

                Sales   Profit
Category
Clothing      2248310   444567
Electronics  22256321  4258542
Furniture    13063762  2399870
Grocery        797596   148153
Stationery     601915   108090

In [20]:
Customer=df.groupby("Customer")[["Sales","Profit"]].sum()
Customer

            Sales  Profit
Customer
Aditya    1637408  253331
Akhil     2088969  437192
Anjali    1636343  247873
Anu       2181621  425429
Arun      2817469  654697
Divya     1282769  259239
Kiran     1591470  313723
Lakshmi   1833916  329242
Manoj     1576864  246208
Meena     2793148  491398
Neha      1590938  262175
Nikhil    1784018  320731
Pooja     2243126  481712
Priya     2323539  496235
Rahul      826114  147428
Ravi      2354172  390052
Sneha     1410967  284564
Suresh    1658293  267532
Swathi    3564632  722643
Vijay     1772128  327818

In [24]:
best_customer=Customer["Sales"].idxmax()
print("best customer:",best_customer)
print("Sales:",Customer.max())

best customer: Swathi
Sales: Sales     3564632
Profit     722643
dtype: int64

In [34]:
sales_report=df.groupby("Category").agg(
        Total_sales=("Sales", "sum"),
        Total_Profit=("Profit", "sum"),
        average_sales=("Sales","mean"),
        total_quantity=("Quantity","sum")
)
print(sales_report)

             Total_sales  Total_Profit  average_sales  total_quantity
Category
Clothing         2248310        444567   23666.421053             526
Electronics     22256321       4258542  229446.608247             529
Furniture       13063762       2399870  114594.403509             630
Grocery           797596        148153    7975.960000             577
Stationery        601915        108090    6403.351064             532

In [25]:
pivot=pd.pivot_table(
    df,
    values="Sales",
    index="Customer",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)

print(pivot)

Category  Clothing  Electronics  Furniture  Grocery  Stationery
Customer
Aditya       60234      1135900     391540     1420       48314
Akhil       190418       995544     826174    58906       17927
Anjali      112207       574194     890550    11286       48106
Anu         379425       498958    1224504    33117       45617
Arun        119341      1984593     637901    75634           0
Divya       113546       490594     619079    34740       24810
Kiran        10363       667444     841585    42948       29130
Lakshmi      39421       691204    1084851     8963        9477
Manoj        28025       954934     498947    64366       30592
Meena       199191      1891910     653513    25406       23128
Neha         33388       792018     675251    50727       39554
Nikhil       38690      1191851     495740    43606       14131
Pooja       138606      1764932     258293    40661       40634
Priya       127397      1648610     437067    94715       15750
Rahul       148714       220621     372506    22599       61674
Ravi        217423      1200764     883071    30560       22354
Sneha        48799      1008372     268155    62055       23586
Suresh      110258      1241462     246482    40473       19618
Swathi       71298      2501531     892993    33241       65569
Vijay        61566       800885     865560    22173       21944

In [26]:
df["Profit_margin"]=(df["Profit"]|df["Sales"])*100

In [27]:
df["Profit_margin"]

0      18553400
1         11100
2        819100
3        357400
4       1009300
         ...
495     1615800
496      988700
497    17944500
498     1605900
499     1599900
Name: Profit_margin, Length: 500, dtype: int64